apiVersion: v1
kind: ConfigMap
metadata:
  namespace: alert-dispatcher
  name: alert-dispatcher-config
data:
  SERVER_PORT: "8088"
  POLL_INTERVAL_SEC: "10"
  SLACK_CHANNEL_P0: "#p0-channel"
  SLACK_CHANNEL_P1: "#p1-channel"
  SLACK_CHANNEL_P2: "#p2-channel"
  SLACK_CHANNEL_DEFAULT: "#alerts"
  alarm-channels.yaml: |
    # Specific alarm name to channel mappings
    alarm_mappings:
      "Redis-CPU-Utilization-breach": "#p0-channel"
      "RDS-Production-Storage-less-than-50GB": "#p0-channel"
      "RDS-CPU-Utilization-greater-than-40": "#p1-channel"
      "RDS-Freeable-Memory-less-than-10GB": "#p2-channel"
      "Staging-CPU-Utilization-greater-than-40": "#p2-channel"
      "WAF-Attack-Rate-greater-than-1000": "#p0-channel"
      
      