apiVersion: v1
kind: Service
metadata:
  namespace: alert-dispatcher
  name: alert-dispatcher-service
  labels:
    app: alert-dispatcher
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8088
    protocol: TCP
    name: http
  selector:
    app: alert-dispatcher